*input:-99029152
L L = 
#include - test45-1
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-2
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-3
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-4
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-5
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-6
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-7
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-8
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-9
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-10
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-11
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-12
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-13
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-14
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-15
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-16
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-17
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-18
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-19
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-20
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-21
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-22
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-23
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-24
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-25
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-26
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-27
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-28
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-29
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-30
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-31
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-32
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-33
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-34
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-35
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-36
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-37
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-38
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-39
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-40
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-41
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-42
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-43
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-44
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-45
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-46
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-47
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-48
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-49
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-50
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-51
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-52
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-53
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-54
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-55
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-56
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-57
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-58
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-59
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-60
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-61
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-62
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-63
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-64
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-65
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-66
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-67
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-68
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-69
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-70
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-71
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-72
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-73
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-74
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-75
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-76
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-77
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-78
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-79
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-80
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-81
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-82
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-83
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-84
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-85
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-86
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-87
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-88
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-89
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*11223344
L L = L
#include - test45-90
;
id S(a?)=1;
argument koef;
	id hx=1;
	id hy=1;
	id hz=1;
endargument;
id koef(t?) = t^2;
.sort
*8446987
